# Built from:
# https://docs.github.com/en/actions/guides/building-and-testing-python
# https://github.com/snok/install-poetry#workflows-and-tips

name: Build and test linkml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    # See https://github.com/snok/install-poetry#running-on-windows
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry==1.*
      - name: Install dynamic versioning plugin
        run: poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install --no-interaction --all-extras
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Generate coverage results
        run: |
          poetry run coverage run -m pytest --with-slow --with-network
          poetry run coverage xml
        shell: bash
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml